# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Infineon Technologies AG 2026.

[toolchain]
channel = "nightly-2026-04-21"
components = [
    "miri",
    "llvm-tools",
    "rust-src",
    "rustfmt",
    "clippy",
    "rust-analyzer",
]
targets = ["thumbv8m.main-none-eabi"]
