# SPDX-FileCopyrightText: Infineon Technologies AG
#
# SPDX-License-Identifier: MIT

[toolchain]
channel = "nightly-2026-04-21"
components = [
    "miri",
    "llvm-tools",
    "rust-src",
    "rustfmt",
    "clippy",
    "rust-analyzer",
]
targets = ["thumbv8m.main-none-eabi"]
