# SPDX-FileCopyrightText: Infineon Technologies AG
#
# SPDX-License-Identifier: MIT

[package]
name = "tock_interrupt_test_app"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
libtock = { git = "https://github.com/tock/libtock-rs.git", rev = "fc89be7d18da55649b5b3d3b98b40c88a78d9ef0" }

[build-dependencies]
libtock_build_scripts = { git = "https://github.com/tock/libtock-rs.git", rev = "fc89be7d18da55649b5b3d3b98b40c88a78d9ef0" }

[features]
default = []
test_unpriv_spe = []
test_loop_token = []

[lints]
workspace = true
