# SPDX-FileCopyrightText: Infineon Technologies AG
#
# SPDX-License-Identifier: MIT

include = [
    "../../../tock/boards/cargo/tock_flags.toml",
    "../../../tock/boards/cargo/unstable_flags.toml",
]

[build]
target = "thumbv8m.main-none-eabi"
