# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Infineon Technologies AG 2026.

include = [
  "../../../tock/boards/cargo/tock_flags.toml",
  "../../../tock/boards/cargo/unstable_flags.toml",
]

[build]
target = "thumbv8m.main-none-eabi"
rustflags = [
  # # todo required for build_scripts but should work without / does work inside the tock repo
  # Output secure veneer library
  "-C",
  "link-arg=--cmse-implib",
  "-C",
  "link-arg=--out-implib=target/thumbv8m.main-none-eabi/psc3m5_secure-veneers.o",
]

[unstable]
config-include = true
