// SPDX-FileCopyrightText: Infineon Technologies AG
//
// SPDX-License-Identifier: MIT

//! Veneer function with spm dependence

// Reentrance protection:
// If a Secure function is not designed to be reentrant (meaning it doesn't
// handle multiple simultaneous instances of itself), a second call could
// corrupt the Secure Stack, bypass Security Logic, or Leak Data.
//
// We use a global secure flag to track if we are currently executing in Secure
// state. This is an alternative to checking a stack seal with the hardware
// stack pointer (SP), because the Rust compiler emits an unpredictable prologue
// for `extern "cmse-nonsecure-entry"` functions, making it fragile to read `[SP
// + offset]`.

// unsafe(no_mangle) is required to ensure these functions are linkable from
// non-secure code. It is unsafe because there could be name collisions.

// The linker's `--cmse-implib` generates the `sg` stub in .gnu.sgstubs and the
// import library when it sees an `__acle_se_psa_xxx_veneer` symbol paired with
// a `psa_xxx_veneer` definition. Non-naked `extern "cmse-nonsecure-entry"`
// functions emit this pair correctly.

/// Retrieve the version of the PSA Framework API that is implemented.
#[cfg(target_arch = "arm")]
#[unsafe(no_mangle)]
pub extern "cmse-nonsecure-entry" fn psa_framework_version_veneer() -> u32 {
    enter_secure_state();
    let res = psa_interface::types::PSA_FRAMEWORK_VERSION;
    exit_secure_state();
    res
}

#[cfg(not(target_arch = "arm"))]
#[unsafe(no_mangle)]
pub extern "cmse-nonsecure-entry" fn psa_framework_version_veneer() -> u32 {
    psa_interface::types::PSA_FRAMEWORK_VERSION
}

// The `psa_version_veneer` and `psa_call_veneer` functions are generated by the
// `define_spm_api!` macro, which has direct access to the SPM implementation.

use core::sync::atomic::{AtomicBool, Ordering};

/// Flag to track if the CPU is currently executing in Secure state.
/// Used to prevent re-entrant calls from Non-Secure to Secure state.
#[cfg(target_arch = "arm")]
static IN_SECURE_STATE: AtomicBool = AtomicBool::new(false);

/// Marks the entry into Secure state and detects illegal re-entrant calls.
///
/// Veneer functions call this on entry to detect re-entrant calls from the
/// Non-Secure world. Because normal Rust functions have an unpredictable
/// prologue, we cannot reliably check if the hardware stack pointer (`SP`)
/// points to a stack seal at the base of the secure stack. Instead, we use
/// this secure global flag to track execution state.
///
/// # Panics
/// Panics if a re-entrant call is detected (i.e. if the flag is already set).
#[cfg(target_arch = "arm")]
#[inline]
pub fn enter_secure_state() {
    if IN_SECURE_STATE.swap(true, Ordering::SeqCst) {
        panic!("Re-entrant veneer call detected");
    }
}

/// Marks the exit from Secure state.
#[cfg(target_arch = "arm")]
#[inline]
pub fn exit_secure_state() {
    IN_SECURE_STATE.store(false, Ordering::SeqCst);
}

/// No-op stub for non-ARM targets so the veneer functions compile everywhere.
#[cfg(not(target_arch = "arm"))]
#[inline]
pub fn enter_secure_state() {}

#[cfg(not(target_arch = "arm"))]
#[inline]
pub fn exit_secure_state() {}
