// SPDX-FileCopyrightText: Infineon Technologies AG
//
// SPDX-License-Identifier: MIT

//! Veneer function with spm dependence

// TODO: Reentrance protection like here: secure_fw/partitions/ns_agent_tz/psa_api_veneers_v80m.c ?
// 2. Why is Reentrancy a Problem?
// If a Secure function is not designed to be reentrant (meaning it doesn't handle multiple simultaneous instances of itself), a second call could:
// Corrupt the Secure Stack: Overwrite local variables or return addresses of the first call.
// Bypass Security Logic: If a function checks a permission at the start and relies on that state, a reentrant call might alter the state while the first instance is still mid-execution.
// Leak Data: State from the first "half-finished" call might be accessible to the second call.

// TODO: Stack Seal https://developer.arm.com/-/media/Arm%20Developer%20Community/PDF/Armv8-M%20Architecture-Stack%20sealing%20and%20why%20it%20is%20needed%20in%20TrustZone%20for%20Armv8-M.pdf

// unsafe(no_mangle) is required to ensure these functions are linkable from
// non-secure code. It is unsafe because there could be name collisions.

/// Retrieve the version of the PSA Framework API that is implemented.
#[unsafe(no_mangle)]
pub extern "cmse-nonsecure-entry" fn psa_framework_version_veneer() -> u32 {
    psa_interface::types::PSA_FRAMEWORK_VERSION
}

// The `psa_version_veneer` function is generated by the `define_spm_api!` macro,
// which has direct access to the SPM implementation.
