// SPDX-FileCopyrightText: Infineon Technologies AG
//
// SPDX-License-Identifier: MIT

//! Veneer functions for Non-Secure to Secure PSA API calls.
//!
//! Each veneer is a naked `cmse-nonsecure-entry` function. The linker places
//! an `sg` (Secure Gateway) stub in `.gnu.sgstubs`; that stub validates the
//! NS→S transition and branches here. On entry the Main Stack Pointer (MSP)
//! must point at a [`STACK_SEAL_PATTERN`] sentinel written during secure boot
//! (see [`crate::startup::jump_to_nonsecure`]). A mismatch indicates an
//! illegal re-entrant call and halts the CPU.

// The `psa_version_veneer` and `psa_call_veneer` functions are generated by the
// `define_spm_api!` macro, which has direct access to the SPM implementation.

use crate::startup::{STACK_SEAL_HI, STACK_SEAL_LO};

// Hand-written CMSE SG stub: LLVM only auto-generates `.gnu.sgstubs` entries
// for non-naked `cmse-nonsecure-entry` functions, so naked veneers need their
// stub emitted manually. The `__acle_se_`-prefixed symbol below matches the
// naming the compiler-generated stubs would otherwise use.
core::arch::global_asm!(
    ".section .gnu.sgstubs,\"ax\",%progbits",
    ".align 5",
    ".global psa_framework_version_veneer",
    ".type psa_framework_version_veneer, %function",
    ".thumb_func",
    "psa_framework_version_veneer:",
    "sg",
    "b __acle_se_psa_framework_version_veneer",
);

/// Retrieve the version of the PSA Framework API that is implemented.
#[cfg(target_arch = "arm")]
#[unsafe(naked)]
#[unsafe(no_mangle)]
pub extern "C" fn __acle_se_psa_framework_version_veneer() -> u32 {
    core::arch::naked_asm!(
        "ldr r0, [sp]",
        "movw r1, #{seal_lo}",
        "movt r1, #{seal_hi}",
        "cmp r0, r1",
        "bne 99f",
        "push {{r4, lr}}",
        "bl {impl_fn}",
        "pop {{r4, lr}}",
        "movs r1, #0",
        "movs r2, #0",
        "movs r3, #0",
        "mov r12, r1",
        "msr APSR_nzcvq, r1",
        "bxns lr",
        "99:",
        "b 99b",
        impl_fn = sym psa_framework_version_impl,
        seal_lo = const STACK_SEAL_LO,
        seal_hi = const STACK_SEAL_HI,
    );
}

fn psa_framework_version_impl() -> u32 {
    psa_interface::types::PSA_FRAMEWORK_VERSION
}

#[cfg(not(target_arch = "arm"))]
#[unsafe(no_mangle)]
pub extern "cmse-nonsecure-entry" fn psa_framework_version_veneer() -> u32 {
    unimplemented!("Only implemented for ARM architectures");
}
