# SPDX-FileCopyrightText: Infineon Technologies AG
#
# SPDX-License-Identifier: MIT

[package]
name = "tock_psa_app"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
libtock = { git = "https://github.com/tock/libtock-rs.git", rev = "fc89be7d18da55649b5b3d3b98b40c88a78d9ef0" }
psa_interface = { path = "../../../spe/psa_interface" }
psa_veneer_client = { path = "../../../spe/psa_veneer_client" }

[build-dependencies]
libtock_build_scripts = { git = "https://github.com/tock/libtock-rs.git", rev = "fc89be7d18da55649b5b3d3b98b40c88a78d9ef0" }

[features]
default = []
# default = ["test_loop_token"]
test_loop_token = []
test_negative = []

[lints]
workspace = true
