# SPDX-FileCopyrightText: Infineon Technologies AG
#
# SPDX-License-Identifier: MIT

name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  tools:
    name: Tools checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Install dependencies
        run: uv sync
      - name: lint
        run: uv run ruff check
      - name: typecheck
        run: uv run ty check
  lint:
    name: Format & Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-env
      - name: Check formatting
        run: inv fmt --check
      - name: Run clippy
        run: inv clippy
      - name: Check spelling
        run: inv check-spelling
        continue-on-error: true
      - name: Run reuse linting
        run: inv reuse
        continue-on-error: true

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-env
      - name: Build all board and app targets
        run: inv build

  test:
    name: Unit Tests & Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-env
      - name: Run tests
        run: inv test --mode unit
      - name: Generate coverage
        run: inv coverage --html
      - name: Upload coverage report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-report
          path: target/llvm-cov/html/

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-env
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y qemu-system-arm
      - name: Run tests
        run: inv test --mode integration

  miri:
    name: Miri
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-env
      - name: Run Miri
        run: inv miri
